apiVersion: v1
kind: Service
metadata:
  name: html-app-svc
spec:
  selector:
    app: html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer   # use NodePort or ClusterIP if no cloud LB